### ISSUE TITLE
Change point size in plot

### ISSUE THREAD

**Issue by riversn** [bradmartin333/XferSuite#100]
Allow right click in parsed map to change point size instead of having to open suite settings.

![image](https://user-images.githubusercontent.com/101815602/161135839-4c9b487d-e1ae-4aa2-bb52-e68b00d74a28.png)

**Comment by bradmartin333** [comment]
added to #98

**Comment by riversn** [comment]
No longer functioning. Changing point size at all does not change plot, but a new plot is being created.

![image](https://user-images.githubusercontent.com/101815602/161843433-d13c862c-0b00-437b-acbb-6ff507af4f84.png)

**Comment by riversn** [comment]
This might be due to customs plotting with their own set 'size' properties, but I figure generic pass/fails from non-custom datasets should still get the 'default size in options' setting applied to it.

**Comment by bradmartin333** [comment]
the customs do use special sizes and the generic pass/fails should still use that number - will still open a new plot for now

**Comment by riversn** [comment]
I figured this one out!

If the "last opened window is a plot" it will correctly apply point size changes through the options menu.

If "the last opened window" is the **XferSuite Window** it will make a new plot with all sizes at '1'.

![image](https://user-images.githubusercontent.com/101815602/161976842-6bae2a23-7d78-4eba-9b67-16189b5bb438.png)

**Comment by bradmartin333** [comment]
ah, cool! will be much more straightforward in the near future
