### ISSUE TITLE
Custom Features

### ISSUE THREAD

**Issue by riversn** [bradmartin333/XferSuite#103]
Fun conundrum. I made a SEYR run to test if a part was present and then a secondary inspection area of the corner of the part to see if it was rotated or not.

I want to plot in the parsed map - Green if Substrate + Twisted alignments pass, Blue if Substrate is there, but failing twisted, and Red if both failing.

![image](https://user-images.githubusercontent.com/101815602/161311857-6fdf3698-6d03-47cf-aa58-c479db85e633.png)

**Comment by riversn** [comment]
The point, is that there's no way to plot specifically If dataset 1 passes & Dataset 2 Fails, then plot as a color (fail or passing doesn't matter).

No way to 'Need Dataset 1' but then also display dataset 2 in some way at the same time.

**Comment by riversn** [comment]
Maybe what I'm looking for is a for two datasets, if both fail, hide/exclude the point from being plotted. (not plot as a fail)

I guess that would be hide/exclude from plot capability.

**Comment by bradmartin333** [comment]
possibility of adding custom to need one bucket

**Comment by bradmartin333** [comment]
make ordered check box list for custom bucket

**Comment by riversn** [comment]
Add size capability for customs too?

In the scenario I want to plot a large submount and the individual units ontop of it?

![image](https://user-images.githubusercontent.com/101815602/161617390-6ef8b388-a346-47c4-9605-c4389217ef98.png)
![image](https://user-images.githubusercontent.com/101815602/161617416-46f7b01a-b021-47f5-b03a-b6fcfc818aec.png)

**Comment by bradmartin333** [comment]
- [ ] show/hide custom features
- [ ] custom color (as well as match backcolor)
- [ ] custom plot order

**Comment by bradmartin333** [comment]
everything set for a new demo version (use same link as before)

**Comment by bradmartin333** [comment]
it's a big one! 
![image](https://user-images.githubusercontent.com/19335151/161658399-ff7f0271-a810-4526-a76d-acff574a92e7.png)
