### ISSUE TITLE
Custom Data Filtering

### ISSUE THREAD

**Issue by riversn** [bradmartin333/XferSuite#105]
Scenario of Seyr measurement run is a different optic than stamp/print array size. (not divisible indexed). Want a way to hide these points. 

Not sure what the best way to do it, either user can highlight individual points and then CTRL+E to exclude them (or right click option) or if there's some way we can have SEYR "hide the last 2 units from the edges of the print field" or something built into the SEYR recipe. Or a separate custom parse option for it?

**Comment by riversn** [comment]
![image](https://user-images.githubusercontent.com/101815602/161601438-de766092-1d0c-4883-9533-20ee7d750ea0.png)

**Comment by bradmartin333** [comment]
Once the full RR RC R C SR SC stuff works - I would suggest finding and deleting data from the report? what do you think?

**Comment by riversn** [comment]
Gonna be kinda hard to do in Excel to manually remove those units... I'm not sure either what the best way to do it is.

**Comment by riversn** [comment]
Maybe it needs to be in XferPrint - when making the metro program and it could autocalc that when the Row/Col amounts overhand the stamp row/col amounts, then it could tell seyr not to care about the last rows.... Idk.

**Comment by bradmartin333** [comment]
I think this would qualify for an external tool

**Comment by riversn** [comment]
The best way to do this, would be User selects/highlights the specific points on the plot. Then a "match subfield row/col" highlights all similar units in each subfield row/col. Then once everything is highlighted, a hide/exclude from plot option. (right right click or Ctrl+H or Ctrl+E)

**Comment by riversn** [comment]
#109

**Comment by bradmartin333** [comment]
I think the way to go is have an Advanced Tool that works similarly to the InlinePositions data filterer. Essentially the same thing that you are saying, but works more like SQL instead of a graphical point and click UI.

**Comment by bradmartin333** [comment]
I can walk you through creating this utility and then you can tinker with it for future XferSuite versions as things evolve

**Comment by bradmartin333** [comment]
added in v3.13
