### ISSUE TITLE
Way to report yield of individual Regions/Rows/Subfields

### ISSUE THREAD

**Issue by riversn** [bradmartin333/XferSuite#107]
Looking for a way to report out yield % of individual region fields, or sub fields.

Best way is probably reporting out a yield map in text format first, then maybe applying it graphically at some point in the future.

![image](https://user-images.githubusercontent.com/101815602/161608970-08533c9b-2c96-45ef-99da-43b6f545d620.png)

**Comment by bradmartin333** [comment]
once #98 is done, this is quite straightforward and the overlay will be toggleable with the right click menu (already added to #98)

**Comment by riversn** [comment]
If it's not been implemented yet, don't close it :p
