### ISSUE TITLE
Crashing when parsing customs + Need Ones

### ISSUE THREAD

**Issue by riversn** [bradmartin333/XferSuite#112]
Not sure, but when I do this in this way it throws an error.

![image](https://user-images.githubusercontent.com/101815602/161840346-d8c7c795-700d-4cfe-9ccf-52c065e36d55.png)

**Comment by riversn** [comment]
If you wanna test it too

X:\Micro Assy Proj\SEYR\PxEngAIO_HeroDisplay\MiddleNonRedundantsite.txt

**Comment by riversn** [comment]
Couldn't repeat this - worked fine every other time I do it

**Comment by bradmartin333** [comment]
Looks like I need to add an error handler if a scatterseries has no scatterpoints

**Comment by riversn** [comment]
It's happened to me three times now but I can't figure out why.... There's some combination of orders with customs + size changing + sitting and letting the program wait for longer than 20s with a window open.

![image](https://user-images.githubusercontent.com/101815602/161993599-c0458716-2527-4099-bd8c-57eb7574ee08.png)

**Comment by bradmartin333** [comment]
everything is changing - so I will get you a new version to test soon
