### ISSUE TITLE
Clicking in blank space in custom selects/deselects the highlighted unit

### ISSUE THREAD

**Issue by riversn** [bradmartin333/XferSuite#114]
Clicking in the blank space below the custom unit will check/uncheck the highlighted unit. I want to _specifically_ deselecting anything when clicking in a blank space.

![image](https://user-images.githubusercontent.com/101815602/161841169-202fc295-00d9-4a78-874a-4ce2ee15d5a3.png)

**Comment by riversn** [comment]
This might be what's happening for #113

**Comment by bradmartin333** [comment]
okay - but it will require 2 clicks to select/deselect

**Comment by riversn** [comment]
Is there a way we can overlay a see-through "unclickable zone" ontop of the box and have it's size change based on the fill of the underneath box? Then when there's a longer list of units in the box, the "unclickable zone will shrink?"

**Comment by riversn** [comment]
@bradmartin333 ^

**Comment by bradmartin333** [comment]
Ah okay.. didn't see that

**Comment by bradmartin333** [comment]
will resolve this in the plot order refactor (you omit custom features by leaving them out of the plot order - no checkboxes, no problem)
