### ISSUE TITLE
Custom offsets are opposite

### ISSUE THREAD

**Issue by riversn** [bradmartin333/XferSuite#125]
When inputting offsets for a custom, negative is plotting in the positive direction and vis versa

![image](https://user-images.githubusercontent.com/101815602/161992559-0c9932cc-00bc-4137-8e42-454100afa154.png)
![image](https://user-images.githubusercontent.com/101815602/161992646-a7de8a69-b658-4706-b020-2ad9bb1ef09b.png)

**Comment by bradmartin333** [comment]
ah okay - easy fix
