### ISSUE TITLE
Region Boarder Overlaps at large Point sizes

### ISSUE THREAD

**Issue by riversn** [bradmartin333/XferSuite#128]
When increasing point sizes, region boarder should feather outwards by same amount - but doesn't. Ends up overlapping.
![image](https://user-images.githubusercontent.com/101815602/162265492-cb7beeb5-3289-4be7-8999-8719d9bbb5bc.png)

**Comment by bradmartin333** [comment]
is it okay to just make it transparent? Some regions butt up against each other 
![image](https://user-images.githubusercontent.com/19335151/162276567-706e92d8-d799-4993-8979-2d5b2bb4b12b.png)

**Comment by riversn** [comment]
No, not okay, nothing visual should be at/around real data.

**Comment by bradmartin333** [comment]
how about a user offset setting?

**Comment by bradmartin333** [comment]
added a bunch more settings

**Comment by bradmartin333** [comment]
255 is max, not 100 - default changed to 255
