### ISSUE TITLE
Toggle features in parsed graph as Base settings/Options

### ISSUE THREAD

**Issue by riversn** [bradmartin333/XferSuite#133]
Allow toggleable options in parsed graph to be set as "startup configuration"

Like, in Xfersuite settings there should be the same options but controlled and set so that when a new graph gets made, it starts with those settings.

![image](https://user-images.githubusercontent.com/101815602/162286320-5e0cf54a-5110-440a-a32a-a6ed352465ee.png)

**Comment by bradmartin333** [comment]
how about just store the last config locally on the config?
