### ISSUE TITLE
Graph Options as Right click

### ISSUE THREAD

**Issue by riversn** [bradmartin333/XferSuite#135]
Change graph options should be right click, not "press any button" I figured you just made it work that way to get it working fast.

![image](https://user-images.githubusercontent.com/101815602/162287254-74be39f2-15c6-4d93-a645-606bda7e79d7.png)

**Comment by bradmartin333** [comment]
it's actually for performance. a click handler uses the plot itself and with huge plots it bogs up the system. i can have it work for both though so either way will work

**Comment by bradmartin333** [comment]
added for right click as well
