### ISSUE TITLE
Stretch Axis's independently of other axis

### ISSUE THREAD

**Issue by riversn** [bradmartin333/XferSuite#137]
In parsed graph, want to be able to stretch X axis without changing Y axis and vis versa.

**Comment by bradmartin333** [comment]
The same was as in the view data plot?

**Comment by bradmartin333** [comment]
copied view data plot code into main results plot

**Comment by riversn** [comment]
This is working correctly as implemented, but I would like this feature to have a bit more usability changes. Specifically, add an axis/bar above the text window & below the graph so that the user can manipulate the axises without having to simultaneously change windows frame sizing. (Y axis would also get a bar)

**Comment by riversn** [comment]
It's actually really interesting, a popped out graph does not have this behavior, it seems to be related to having the text window/area below the plot there.

**Comment by bradmartin333** [comment]
Ya, I fudged the main form to work with the text area beneath it. Since it can only use whole numbers, I can see where things would get messed up: https://github.com/bradmartin333/XferSuite/blob/4e9b5285869219f6d20f092b8da23114f6b6c4eb/XferSuite/Apps/SEYR/Results.cs#L510
