### ISSUE TITLE
Drag custom features between forms

### ISSUE THREAD

**Issue by riversn** [bradmartin333/XferSuite#140]
Think this one is doable?

![image](https://user-images.githubusercontent.com/101815602/162297598-4c874a3b-15a8-4a1d-b8fb-ee926f1ba52a.png)

**Comment by bradmartin333** [comment]
while I am not going to prioritize this, it does reveal a bug where if you load a custom feature from, say, PxEng to Murphy it would blow up

**Comment by bradmartin333** [comment]
okay, I prevented that error - but I am gonna say no to this one as I already implemented the save and load

**Comment by bradmartin333** [comment]
Closing for now with the addition of load all custom features
