### ISSUE TITLE
Adding more than 3 'levels' in Need One not shown

### ISSUE THREAD

**Issue by riversn** [bradmartin333/XferSuite#147]
If you drag and make more than '3 levels deep' in a 'connection' in Need one chart, the 3rd and below layers aren't shown.

![image](https://user-images.githubusercontent.com/101815602/162471525-478406e0-b34e-45fd-9164-c11f52a03dc9.png)

**Comment by bradmartin333** [comment]
feature should not allow drop on tree nodes! nice find
