### ISSUE TITLE
Toggleable legend for results plot

### ISSUE THREAD

**Issue by bradmartin333** [bradmartin333/XferSuite#148]
Custom features warrant a legend

**Comment by bradmartin333** [comment]
I spent some time making the legend... And then realized the custom bucket is a legend... However, scottplot has this feature where you can toggle different series visibility by clicking it in the legend. I don't know if that can be achieved in winforms, though. I'll mark this as ongoing because it will take some tinkering.

**Comment by bradmartin333** [comment]
I think all these features are provided by the custom bucket... if you make a sketch of what you want it to look like (popout the bucket or somethin) I will reopen

**Comment by riversn** [comment]
Selecting a unit in a legend should also select/highlight/bring to forefront the units in the graph. This is a wanted feature. 

Basically, the legend is the plot order (except if specific customs are hidden don't show them even though they would be visable in the plot order page). With additional functionality - rename units in the legend separately from custom name or plot ordername, rename legend title, and select/highlight ability above^
