### ISSUE TITLE
Plot customization

### ISSUE THREAD

**Issue by riversn** [bradmartin333/XferSuite#150]
Bold or increase font size to make it more readable. No whitefill underneath. Keep font color black

Have option to not put ontop of region but to right to region label.

**Comment by riversn** [comment]
![image](https://user-images.githubusercontent.com/101815602/162473756-b8dad1df-66a8-4b44-b663-40b3df60eb63.png)

**Comment by bradmartin333** [comment]
Some of these already exist in settings. I think I can make them user draggable for the second point.

**Comment by bradmartin333** [comment]
all added
