### ISSUE TITLE
Changing plot order removes all points from graph

### ISSUE THREAD

**Issue by riversn** [bradmartin333/XferSuite#156]
Changing the plot order will not apply changes to graphs and instead make it blank. All points and info in graph become blank. Re-parsing the plot plots everything correctly.

**Only happens when graph is zoomed in/not at starting aspect ratio.**

![image](https://user-images.githubusercontent.com/101815602/162747907-1f2077c6-43a7-4234-9ebf-d71870b25360.png)

**Comment by bradmartin333** [comment]
I wasn't able to repeat this? Each time the window grows/shrink to match the aspect ratio again and autoscales the axes.
