### ISSUE TITLE
Move yield report boxes

### ISSUE THREAD

**Issue by riversn** [bradmartin333/XferSuite#162]
Would like to be able to move/change where the yield boxes are displayed. Right now they cover a lot of the data.

![image](https://user-images.githubusercontent.com/101815602/165152116-14e9f064-738a-4006-acb6-2e9046e7ce2c.png)

**Comment by bradmartin333** [comment]
There's an option for that in settings. True false

**Comment by riversn** [comment]
Cool, a bit hard to read this way, maybe don't show parentheses around the region, and separate yield and region info by a '|' ?

![image](https://user-images.githubusercontent.com/101815602/165152786-be1f82ca-a5b0-479c-8c2f-1520ca5939e0.png)

**Comment by riversn** [comment]
idk, it's good as is, no big deal

**Comment by riversn** [comment]
Nvm, not sure what the best thing to do, but when the strings are too big, need to figure out how to make it more readable.

![image](https://user-images.githubusercontent.com/101815602/165156366-76e43f48-9ad3-4ec7-9310-1cc2d84d3bc1.png)

**Comment by bradmartin333** [comment]
There's a param for text size. Those params are easy to add if you think of
them.
