### ISSUE TITLE
Add 'open parse seyr menu' in legend window

### ISSUE THREAD

**Issue by riversn** [bradmartin333/XferSuite#184]
Add 'open parse seyr menu' in legend window.

When seyr parse menu is hiden or not visable, but legend is, I want to open it again easily.

**Comment by riversn** [comment]
Add a button to reopen (bring forward) the parse menu from the image viewer.

**Comment by bradmartin333** [comment]
need a visual aid for this one

**Comment by bradmartin333** [comment]
for nomenclature, these are the forms:
- **ParseSEYR** (opens when you open a SEYRUP file)
- **PassFailUtility** (opens when you double click a feature)
- **ImageScroller** (popped up during PassFailUtility when you click a histogram bar and images are saved for that feature)
- **RegionBrowser** (opens when you click Plot)
- **Inspection** (opens when you click on a point in RegionBrowser and images are present)
