### ISSUE TITLE
Add way to plot failing points from a criteria

### ISSUE THREAD

**Issue by riversn** [bradmartin333/XferSuite#196]
Maybe a toggle check mark in the pass criteria table?

Want a way to swap what gets plotted in the color in that table. Like, if I want to plot _failing_ Red only in a certain color, not passing.

**Comment by riversn** [comment]
Manipulating the criteria distribution to do this isn't the answer...

Like if I want to plot passing **_and_** failing parts of the same criteria at the same time, I'd want to be able to have control over the main criteria branch from the upper table, then be able to say plot both or something....

**Comment by bradmartin333** [comment]
a criteria cannot contain both passing and failing data points by definition, but maybe I am missing the point? might need a visual aid

**Comment by riversn** [comment]
A criteria is a set of points that are passing right? What about the set of point that are not in the passing window and are therefor failing?

Right now, It collects passing points great, but I want to plot the failing points as well sometimes.

![image](https://user-images.githubusercontent.com/101815602/174138177-1610f19e-0b5b-490c-8056-2f17b5ab47a0.png)

**Comment by bradmartin333** [comment]
all criteria are plotted unless pass fail mode is on (then pass = green and fail = red)

how should it behave differently?

**Comment by riversn** [comment]
2 criteria in top table.

This generates a combo of:

- **A:** Criteria A = Pass, Criteria B = _Fail_
- **B:** Criteria A = _Fail_, Criteria B = Pass
- **AB:** Criteria A = Pass, Criteria B = Pass
- **Null:** Criteria A = _Fail_, Criteria B = _Fail_

What I want to plot is **A** Failing parts _only _ (not **B** passing) and **AB** passing. Right now there's not a combo to do that without _also_ plotting **B** passing at the same time.

**Comment by bradmartin333** [comment]
Is this for the standard plot or the pass fail plot?

**Comment by bradmartin333** [comment]
If I am understanding you correctly, you want another checkbox next to "Pass" to be able to toggle plotting (instead of, say, changing the color to white)?
