### ISSUE TITLE
Window copy is expanded

### ISSUE THREAD

**Issue by riversn** [bradmartin333/XferSuite#204]
Copy entire window captures an image wider than the actual window. (you get brackground)

![image](https://user-images.githubusercontent.com/101815602/174353519-ac3f0442-c075-4358-ac7b-a00b3045372c.png)

**Comment by bradmartin333** [comment]
![image](https://user-images.githubusercontent.com/19335151/174354182-d5f474fe-591c-4f10-b539-12dd394d6076.png)

this good?
