### ISSUE TITLE
Add represitation image to distribution viewer

### ISSUE THREAD

**Issue by riversn** [bradmartin333/XferSuite#209]
![image](https://user-images.githubusercontent.com/101815602/175118219-4f409bae-e67c-4a03-8d93-ca62d31d8485.png)

**Comment by bradmartin333** [comment]
this pic is probably pixelated enough to be okay to post :)

**Comment by bradmartin333** [comment]
you can unlock this feature if you have one 1 feature with image saved and that feature's criteria string is `img` exactly
