### ISSUE TITLE
RC font

### ISSUE THREAD

**Issue by riversn** [bradmartin333/XferSuite#214]
Add options to not plot yield brackets

![image](https://user-images.githubusercontent.com/101815602/176185252-dece8275-6fd7-427f-a21f-31f8b248cb6d.png)

**Comment by riversn** [comment]
Also, tie the yield bracket font to the row/col font, not yield. Looks real bad when it's tied to the yield font

![image](https://user-images.githubusercontent.com/101815602/176186653-c50bc4db-2687-413d-94ed-2f4cb6352c42.png)

**Comment by bradmartin333** [comment]
I can toggle the brackets but I cannot split fonts within the label
