### ISSUE TITLE
Tool to swap A grid with null B grid

### ISSUE THREAD

**Issue by bradmartin333** [bradmartin333/XferSuite#221]

**Comment by riversn** [comment]
I think this is the right ticket for this, made a new stamp seyr run with only using the A grids in gridmaker (no B/Cs) but it won't plot correctly. Images are still working fine when viewing the criteria window, but nothing comes up when clicking in the plot window.

![image](https://user-images.githubusercontent.com/101815602/180465590-379e1cc2-14eb-4527-bd72-b65aed3005cd.png)

**Comment by bradmartin333** [comment]
I can make a new Advanced Tool that swaps the A and B grid. This ticket is automating what the user can do themselves (Excel or other)or prevent when setting up the GridMaker.

**Comment by bradmartin333** [comment]
@riversn The bottom tool in the Advanced Tools selector is a very simple UI that accomplishes this task
