### ISSUE TITLE
Add Pass Fail Data Info

### ISSUE THREAD

**Issue by riversn** [bradmartin333/XferSuite#233]
I want Total number of units called out at top, Total fails (of all regions)

Then a table with %yield, # fails, # passing broken by Regions

Maybe a button in the data inspector window to pop up the info. Doesn't need to be part of the plot window

**Comment by bradmartin333** [comment]
added setting to show info above the percentage
![image](https://user-images.githubusercontent.com/19335151/179014967-a213848c-4ba2-4211-958f-a8f16387c241.png)
