### ISSUE TITLE
Fail inspection routine

### ISSUE THREAD

**Issue by bradmartin333** [bradmartin333/XferSuite#235]
New window for assigning reason to fail to append a column to the data rows export

**Comment by bradmartin333** [comment]
@riversn Would you like the entered `Fail Reasons` to be saved to the SEYRUP when using `Save As` as well?

**Comment by bradmartin333** [comment]
- [ ] save
- [ ] load
- [ ] copy
- [ ] close

**Comment by riversn** [comment]
> @riversn Would you like the entered `Fail Reasons` to be saved to the SEYRUP when using `Save As` as well?

Probably we do?

**Comment by bradmartin333** [comment]
@riversn Just uploaded a new v4.2 with these changes - find the download link on the XferSuite github page or via the documentation button in the settings panel of XferSuite
