### ISSUE TITLE
Transpose A grid option

### ISSUE THREAD

**Issue by riversn** [bradmartin333/XferSuite#236]
changing Flip X and Y doesn't change axes, maybe I'm not understanding what it's supposed to do.

I'd like a setting that swaps the X axis for the Y axis (plots X along Yaxis).

**Comment by riversn** [comment]
Yeah, RR with RC. We turn the display 90* then seyr it sometimes depending on how we do the printing. But you have to be careful to match the inner rows/col correctly too

![image](https://user-images.githubusercontent.com/101815602/178557955-69d70f62-484a-4c9b-9301-d94d5ffc50ab.png)

**Comment by bradmartin333** [comment]
do you need the x and y axis labels to swap as well? or keep those the same?
