### ISSUE TITLE
Large file options

### ISSUE THREAD

**Issue by riversn** [bradmartin333/XferSuite#237]
Provide link to download more RAM.

Would be nice for a quick workaround if we could have an option in grid maker or seyr itself if it notices the run will be big, break the A grids and save them as separate Seryups. That way we could open them one by one ourselves instead of totally being unable to open the huge syrup file.

As an aside to that, could we then when we go to import into xfersuite, in the open seryup file, highlight multiple seryups to join them?

**Comment by riversn** [comment]
Haven't heard about the VM box yet... But please don't do work

**Comment by bradmartin333** [comment]
- [ ] try to optimize
- [ ] try external DB
- [ ] try splitting files

**Comment by bradmartin333** [comment]
![image](https://user-images.githubusercontent.com/19335151/179010538-22cadb9e-9113-4711-acd3-e97f789506de.png)
![image](https://user-images.githubusercontent.com/19335151/179010636-a343c02c-3a45-4ede-bf09-b5337b95435a.png)

when the SEYRUP file is bigger than the settings param (which is in MB), it will prompt about splitting the file

**Comment by riversn** [comment]
settings param (which is in MB) Label  (MB) in settings title name pls.

**Comment by riversn** [comment]
Make the split limit 100mb as default too

**Comment by bradmartin333** [comment]
> Also, when the split files are plotted, the RC/RR labels along the axis don't keep the original RC/RR labels. (they become 1,1)

Currently the exported files read `name_(X,Y)` not `name_(RR,RC)`- do you want me to swap to that?

**Comment by riversn** [comment]
Actually, it looks like the RR axis is correct and gets '2' but maybe there's only an issue with the RC axis

**Comment by bradmartin333** [comment]
> looks like the RR axis is correct and gets '2' but maybe there's only an issue with the RC axis

yeah - fixed that - one liner bug (same with the missing (1,1))

> Also, would be nice if it put the split files in a new folder instead of just adding to the same location.

the exported SEYRUP files will be in an auto-generated folder with this naming convention: `15Jul2022-09-59-16`
