### ISSUE TITLE
Save/load criteria

### ISSUE THREAD

**Issue by riversn** [bradmartin333/XferSuite#238]
Would like custom colors to get saved with 'save as seyrup' function and the plotted critera to save with the colors that get set.

Right now, you have to remake the plotted criteria and reset the colors when you open a saved syrup

![image](https://user-images.githubusercontent.com/101815602/179017279-b9f61d1a-1c22-41d5-90a4-07fbbec064c1.png)

**Comment by bradmartin333** [comment]
For this to be possible, criteria would need to be saved/loaded. [These parameters](https://github.com/bradmartin333/XferSuite/blob/36b1972c26c1a73ad06878c44eabdfa6b6558e84/XferSuite/Apps/SEYR/Criteria.cs#L9-L11) belong to criteria, which are generated by features upon plotting. It could work, but would require a good amount of testing and error prevention.

**Comment by bradmartin333** [comment]
this went well! all done - if you don't have any issues with the stuff I added yesterday, I will make a new release with this feature. I expect you will want some changes to the Inspection Routine form (make sure you use all 4 arrow keys!). Hopefully the file splitting works. 😎
