### ISSUE TITLE
Inspection Report Output

### ISSUE THREAD

**Issue by riversn** [bradmartin333/XferSuite#241]
Would it be too much work for the inspection report to output the failing units in a table with the 'fail' input by the user?

Table would be:

Unit info, (row/col), fail reason

A button for "output report" would be nice.

**Comment by bradmartin333** [comment]
it gets automatically copied to clipboard when you click "Done" - does that suffice?

**Comment by riversn** [comment]
Yeah! that does work, maybe a specific button to copy report to clipboard instead of it being done without you knowing that it happened.

**Comment by bradmartin333** [comment]
Using #235 for this
