### ISSUE TITLE
Grid R/C not correct when not starting a 1,1 A Grids

### ISSUE THREAD

**Issue by riversn** [bradmartin333/XferSuite#244]
Used gridmaker to skip all of col 1 and start the inspection on col 2, but when plotting the plot messes up a bit.

![image](https://user-images.githubusercontent.com/101815602/182851200-22f48894-36fc-485c-9d06-a82d164178b9.png)

**Comment by bradmartin333** [comment]
neat bug, easy fix - but I don't have very good test data for that sort of thing. I will make a new dev installer and you can give it a go without a full release. standby on that.

**Comment by bradmartin333** [comment]
![image](https://user-images.githubusercontent.com/19335151/182868317-86d7fc48-af41-4703-aab0-f08e8b63c3ba.png)

**Comment by bradmartin333** [comment]
Okay, new installer is up - you can download from the documentation page

**Comment by riversn** [comment]
Latest version fixed it!
