### ISSUE TITLE
Region Inspection Routine Crashes

### ISSUE THREAD

**Issue by riversn** [bradmartin333/XferSuite#246]
Not sure what changed, but region inspection routine doesn't work anymore. Just errors completely.

![image](https://user-images.githubusercontent.com/101815602/201676713-44e17bb3-14d7-431b-8e57-c39848051602.png)

**Comment by bradmartin333** [comment]
Could be something unprecedented - need a file to test with...

**Comment by riversn** [comment]
It's a problem when the C grid in Gridmaker is not 1,1

If there's any grids in C grid for gridmaker grouping the seyr run by SubRegions, region inspection fails.

**Comment by riversn** [comment]
[Test Print_Testing.zip](https://github.com/bradmartin333/XferSuite/files/10003764/Test.Print_Testing.zip)

**Comment by riversn** [comment]
When you break the regions out "Split B Grid" option, so that C grids are printed, Region inspection works, but when you don't and the C Grids are not 1,1; it doesn't work.

Also, as another bug, the Split B Grid option setting is not saved, if you set to true, it reverts back to false. And once you turn the Split B grid on (set to true) if you turn it off, the plot does not go back - it stays plotting as if it's 'true'

![image](https://user-images.githubusercontent.com/101815602/201682947-c2dd5347-ced3-4108-bbd0-21b6621b820f.png)

This works:
![image](https://user-images.githubusercontent.com/101815602/201682691-f5613ac9-c46f-45b3-aa7f-96b89398807e.png)

This doesn't work:
![image](https://user-images.githubusercontent.com/101815602/201683407-5918ce50-242d-4829-bfec-84d9318442f2.png)

**Comment by bradmartin333** [comment]
>Also, as another bug, the Split B Grid option setting is not saved, if you set to true, it reverts back to false. And once you turn the Split B grid on (set to true) if you turn it off, the plot does not go back - it stays plotting as if it's 'true''

Not a bug - as the info for the Split B options says: "Irreversibly and uncontrollably creates more plotted regions. Might cause the software to stall if not an appropriate application of the feature. Need to close and reopen .SEYRUP file to reset. Toggles itself off after use as it greatly increases processing time."

I would need the un-split file to test the region inspection error. I can technically rebuild the original file, but it would be a lot easier to debug with the original to start with.

**Comment by riversn** [comment]
Here's original
[Test Print_18.zip](https://github.com/bradmartin333/XferSuite/files/10003902/Test.Print_18.zip)

**Comment by bradmartin333** [comment]
thx for file, interesting bug - seems easy to fix - I will try to get a new version out soon.
anything else you want while I am refamiliarizing myself with the code?
