### ISSUE TITLE
Copy Yield values as table

### ISSUE THREAD

**Issue by riversn** [bradmartin333/XferSuite#250]
Would really love a way to copy the yield values by RR/RC/R/C/SR/SC in a table that I can copy/paste from

![image](https://user-images.githubusercontent.com/101815602/202246686-00b41be0-76fd-4ab1-9778-09c81e914bbd.png)

**Comment by bradmartin333** [comment]
Like this?

| R  | C | RR | RC | Yield % |
| --- | --- | --- | --- | --- |
| 1 | 1 | 6 | 1 | 24 |
| 1 | 1 | 6 | 2 | 37 |

**Comment by bradmartin333** [comment]
added under `Copy Yield Table`

**Comment by riversn** [comment]
Just a column for the 'passing' criteria names
![image](https://user-images.githubusercontent.com/101815602/203140141-2789e9a4-c1cd-42a7-b502-ddfc459feb9f.png)

**Comment by bradmartin333** [comment]
how does this look?

```
Passing Criteria
	14	blue-led green-led red-led
	13	green-led red-led
	4	green-led

R	C	RR	RC	Yield%	#Units
1	1	1	1	62.15	2880
1	1	3	3	90.97	144
1	1	4	4	65.78	14256

```

**Comment by riversn** [comment]
No, the name of the criteria needs to be on the side of the table, repeated

**Comment by riversn** [comment]
![image](https://user-images.githubusercontent.com/101815602/203142656-b6ad4b44-3263-4f52-ac85-edb45e23e542.png)

**Comment by riversn** [comment]
![image](https://user-images.githubusercontent.com/101815602/203142688-8e04bf48-6c04-4699-98f9-08d8faacbead.png)

**Comment by bradmartin333** [comment]
how is this?

![image](https://user-images.githubusercontent.com/19335151/203143568-3c6c91f1-67e4-431b-992a-ecdbc9108ab7.png)

**Comment by riversn** [comment]
Yea!
