### ISSUE TITLE
Triggering Pass/Fail manualy does not change pass/fail value

### ISSUE THREAD

**Issue by riversn** [bradmartin333/XferSuite#251]
Triggering Pass/Fail manualy does not change pass/fail value

This button:
![image](https://user-images.githubusercontent.com/101815602/202247057-59dcdccb-e930-4aa4-aea3-bb79f16eac73.png)

Note: if you plot by IMG only, then pressing that button does change the pass/fail, but not if you are plotting a criteria

**Comment by bradmartin333** [comment]
have you tried replotting by clicking "Plot" right after changing Fail -> Pass?

**Comment by bradmartin333** [comment]
Found the bug. It seems this feature was hacked in such a way to only utilize features with images (As that is all you can realistically view to judge that is should be changed). I added another hack that will apply the same pass state to all features at the same X Y location. This might take a bit to process with very large files - let me know if it causes more issues and I can add performance improvements.
