### ISSUE TITLE
X/Y map plot not representative of actual SEYR Score

### ISSUE THREAD

**Issue by riversn** [bradmartin333/XferSuite#253]
Something is getting messed up with how the fails are mapping. The SEYR Score is off by exactly 100, so it's passing parts that should be failing.

![image](https://user-images.githubusercontent.com/101815602/202252306-cfb5369f-c42a-4246-a2c1-8398588e47b5.png)

![image](https://user-images.githubusercontent.com/101815602/202252148-76048177-ff4f-4cc1-997b-f1d1b9e8d67f.png)

**Comment by riversn** [comment]
This might have been a lighting issue actually... maybe not a SEYR scoring/mapping issue. I might have confused the locations of the two failing points

**Comment by riversn** [comment]
Yeah, it was a lighting thing, I was picking up the vacuum ring underneath and that was making that point darker than the rest.

**Comment by bradmartin333** [comment]
Can this be closed?

**Comment by riversn** [comment]
Closed, user lighting settings caused this
