### ISSUE TITLE
Copy Data makes extra columns depending on criteria name with space

### ISSUE THREAD

**Issue by riversn** [bradmartin333/XferSuite#254]
Copy Data makes extra columns depending on criteria name with space
![image](https://user-images.githubusercontent.com/101815602/203081606-15a46d1e-f215-4c05-a605-d8fddc4173ef.png)
![image](https://user-images.githubusercontent.com/101815602/203081743-f9ddaefe-8a6c-4884-a837-10b30c0e0931.png)

**Comment by bradmartin333** [comment]
spaces will now be automatically replaced with a backtick, which looks like this `

spaces are reserved for the legend string within the Criteria panel (like underscores are reserved for redundant grouping), but I don't want to break any SEYR projects, so this bandaid should work
