### ISSUE TITLE
Add tag on fail table

### ISSUE THREAD

**Issue by riversn** [bradmartin333/XferSuite#255]
Would you be able to label which criteria is failing on this table? When we have a bunch, it's hard to see which is the problem one

![image](https://user-images.githubusercontent.com/101815602/203575889-5c688d45-5f07-44df-b8d7-abf5552d4fa3.png)

**Comment by bradmartin333** [comment]
Great idea!

![image](https://user-images.githubusercontent.com/19335151/203580301-92bc2dae-bdab-4014-b7a4-42330fe2836c.png)

About to update current version (So you will have to manually download it from the tinyurl). Give it 10 minutes or so.

**Comment by riversn** [comment]
Oh my gosh, I love this update. Makes it so nice to quickly see at a glance which one is failing. *Chefs Kiss*
![image](https://user-images.githubusercontent.com/101815602/212922401-e3178b5a-1968-40c7-a5bb-dcd2974697d4.png)
