### ISSUE TITLE
Auto Name combining behavior

### ISSUE THREAD

**Issue by riversn** [bradmartin333/XferSuite#257]
Can we remove the auto-name combining for redundancy behavior?

Or maybe 'if nothing infront of number, don't remove the number'

![image](https://github.com/bradmartin333/XferSuite/assets/101815602/050132b6-a484-4d86-9b6f-f65cda1ebaf2)

**Comment by bradmartin333** [comment]
i'm confused about this one - could you make a table of desired results?

**Comment by riversn** [comment]
The criteria string is auto dropping the numbers, (combining the criteria into one, i.e. LED1, LED2, LED3 are having the numbers dropped and the criteria string gets autoformated to 'LED' for all 3, when it'd be nice to just keep it separate.) If the user wants to combine or group criteria, they can do that themselves.

**Comment by bradmartin333** [comment]
okay - do you want it to be an option to auto drop numbers? or just never do it?

**Comment by riversn** [comment]
Probably just never do it. for a user it's easy now to highlight all the ones they want and group them together

**Comment by bradmartin333** [comment]
took a while, but found it in ParseSEYR.cs

`Regex.Replace(input, @"\d", "").Replace(" ","-").Replace("_","-").ToLower()`

I will make it 

`input.Replace(" ","-").Replace("_","-")`

![image](https://github.com/bradmartin333/XferSuite/assets/19335151/08daaaad-2f25-40ff-9353-eb0390084e58)
