### ISSUE TITLE
Xferprint v4.8 doesn't parse New SEYRdesktop v1.4

### ISSUE THREAD

**Issue by riversn** [bradmartin333/XferSuite#258]
Xferprint v4.8 doesn't parse New SEYRdesktop v1.4

![image](https://github.com/bradmartin333/XferSuite/assets/101815602/ba7ebfff-cf36-458a-b50c-af47a73eea75)

**Comment by bradmartin333** [comment]
SEYRdesktop is a hack and will never work like this. you will have to copy paste the position data from a true file into the SEYRdesktop file

**Comment by bradmartin333** [comment]
this is due to https://github.com/bradmartin333/SEYR/issues/129, not XferSuite or SEYR - but I will try to fix it in SEYRdesktop with more hacking

**Comment by bradmartin333** [comment]
it is fixed - SEYR desktop will now properly load images from an /images folder in a SEYR directory... whyyyyyyy did I make it like this... oh yeah, cuz every coordinate system disagrees with each other.
