### ISSUE TITLE
Fingerprint plots not shown

### ISSUE THREAD

**Issue by xdckneeburg** [bradmartin333/XferSuite#261]
Hi Brad!  Hope you are doing well!

[Inlinepositions (5).txt](https://github.com/user-attachments/files/18010907/Inlinepositions.5.txt)

This inlinepositions file won't display fingerprint plots.  It is 20 prints of a 5x5 stamp. Can you take a look?

Thanks!

Dave

**Comment by bradmartin333** [comment]
hey Dave! good to hear from you.

i loaded up the file as was able to plot both fingerprint and angleprint plots by increasing the xy thresholds in the settings panel with the respective plots selected.

i will leave this issue open in case you would like the default threshold values to be adjusted.

**Comment by xdckneeburg** [comment]
Oh I see now.  This brings up a related issue - if the print results have a large median, (like here ~2 microns) -- that magnitude dominates the vector plot.  Can you normalize the vector plots?  (Subtract the median X and median Y from each point??)

**Comment by bradmartin333** [comment]
does this look correct? new toggle in settings
![Screenshot 2024-12-04 212930](https://github.com/user-attachments/assets/4b295c17-d918-4ee7-a68a-e33e795abb96)
![Screenshot 2024-12-04 212920](https://github.com/user-attachments/assets/af9ffd55-29b2-4849-89e6-fa737148d428)

**Comment by xdckneeburg** [comment]
It looks like the resulting vectors are all up/down in Y.  Is that right?  If you look at the box plots, the X and Y whiskers are close to the same size (maybe X a little bigger).  So there should be some diagonal arrows.

Also check this file.  Its from the standard 40x40 stamp where the median is close to zero, so it will show rotation before applying the removeMedianError, and probably look very similar afterwards.
[Inlinepositions (SAT1 combined data) (1).txt](https://github.com/user-attachments/files/18026141/Inlinepositions.SAT1.combined.data.1.txt)

**Comment by bradmartin333** [comment]
correct about the SAT1 dataset

![Inlinepositions 5Fingerprint2](https://github.com/user-attachments/assets/533abc89-6e88-4f30-bf54-d0da5587fb01)

the vectors are slightly diagonal, but the arrowheads are hard to read with a small vector

![bad_arrow](https://github.com/user-attachments/assets/21a28f55-5c12-4994-a61d-a633a4ad5838)

this arrow is pointing slightly SW, but I have some work to do in order to make it look correct

**Comment by bradmartin333** [comment]
ok, figured it out... the axes are smushed... if you hover over the x axis and use the mouse scroll wheel you can "straighten" the vector arrow

v4.10 seen here
![aaa](https://github.com/user-attachments/assets/d8ac99f8-83c3-4c98-87e4-07fd67156075)

i rewrote the arrow part as seen here
![bbb](https://github.com/user-attachments/assets/6d95b1c8-116a-4444-bfae-492347273c22)

and it looks a bit better

i can made a new version with correctly scaled axes by default and the new arrowhead function

**Comment by bradmartin333** [comment]
[XferSuiteDemo_v4-11.zip](https://github.com/user-attachments/files/18039623/XferSuiteDemo_v4-11.zip)

Demo Changelog
- Fingerprinting 
  - settings option to remove entire dataset median error XY (not automatic, could prompt user if point count == 0)
  - new arrowhead function
- Angleprinting
  - reduces default point magnitude from 200 to 2 (looks good with SAT1 dataset)
- All inlinepositions scatterplots
  - maintain aspect ratio when plotting
  - replot on window resize (maybe remove for performance?)

**Comment by xdckneeburg** [comment]
Thanks!  We're almost there -- just strangeness with "scales and tails".  I don't see any arrow tails like you have in a zoomed snapshot above.  And I need to use a magnitude of 45000 to view a print.
![scale45000](https://github.com/user-attachments/assets/cf811d8c-8312-421e-b57d-dfc55698d665)
![notail](https://github.com/user-attachments/assets/5eed6c62-ce62-4fc9-9ce1-713a4af007fb)

**Comment by bradmartin333** [comment]
The tail is there, but it is very very small. The magnitude only applies to the arrow as the tail was meant to always be true XY values. For this specific plot, it makes sense to multiply everything - I will make that change.

**Comment by bradmartin333** [comment]
[XferSuiteDemo_v4-11-2.zip](https://github.com/user-attachments/files/18066130/XferSuiteDemo_v4-11-2.zip)

new demo with better vector plotting

**Comment by xdckneeburg** [comment]
I like the arrows!  But one more thing - I made a fake file for showing/displaying median removal (normalization).  The Artifact file has one line of 5 points with slight rotation about middle point.  Then the "plusMED" file adds 0.002 to each value.  When the median is removed the plot should look like the first Artifact file.
![image](https://github.com/user-attachments/assets/c7d43a26-2bd8-44af-a83c-b1b0291a4f77)
[ArtifactInLinePosplusMED.txt](https://github.com/user-attachments/files/18067275/ArtifactInLinePosplusMED.txt)
[ArtifactInLinePos.txt](https://github.com/user-attachments/files/18067276/ArtifactInLinePos.txt)

**Comment by bradmartin333** [comment]
ah okay - i accidentally flipped the sign between the two demo versions

[XferSuiteDemo_v4-11-3.zip](https://github.com/user-attachments/files/18067797/XferSuiteDemo_v4-11-3.zip)

i notice that the color mapping is off when using this feature and i can fix that, too (need to get color vals with the new offset applied)

**Comment by bradmartin333** [comment]
[XferSuiteDemo_v4-11-4.zip](https://github.com/user-attachments/files/18068117/XferSuiteDemo_v4-11-4.zip)

corrected vector colors when using remove median option

**Comment by xdckneeburg** [comment]
Awesome!!!!!!!!!!!!! _before/after median removal on inline(5)_

Thank you!!!

![image](https://github.com/user-attachments/assets/786e805e-444d-40b8-b204-08272cde9650)

**Comment by bradmartin333** [comment]
nice! i will make an official v4.11 release soon
