### ISSUE TITLE
Allow drag between Require and Buffer zones

### ISSUE THREAD

**Issue by riversn** [bradmartin333/XferSuite#77]
Can't reset dataset to buffer zone by dragging. would like to be able to.

![image](https://user-images.githubusercontent.com/101815602/158831856-17dd5276-9768-4036-8f50-1bc9de9fd963.png)

**Comment by riversn** [comment]
Scenario:

I click Smart sort because it does 90% of what I want, but then want to only move the 'required' zone back but still run parse with everything in a nice tree under 'need'.

We need a way to remove individual items from the zones when there's a large number of them.

![image](https://user-images.githubusercontent.com/101815602/159538470-2aef19f5-a460-4159-826b-272a1aa3d55f.png)

**Comment by riversn** [comment]
Either drag and drop function, or a highlight and remove button

**Comment by bradmartin333** [comment]
following the smart sort documentation will alleviate this

**Comment by riversn** [comment]
Sure, but the point is, there will always be sometimes when things go wrong. Even if you think you've set it up correctly. 

Take this scenario:
I have 108 individual units in one inspection unit (maybe a little exaggerated but not far fetched in a production setting). I, the user, thought I had named everything correctly, and ran an overnight seyr inspection so that smart sort would be able to sort things correctly. When reviewing the data the next day, I come to find out that one name was off, and instead of easily being able to move the one dataset back and forth from the individual boxes, your solution is to rename the unit, and re-run the entire inspection, or manually input (drag and drop) all 100+ datasets to the correct fields.

The user is not always going to be able to even have the sample or tool time to re-run an entire inspection with the right nomenclature for smartsort to act correctly.

Maybe there's another solution I'm not thinking about that would be easier to implement in the time being.

**Comment by bradmartin333** [comment]
changed my mind - find&replace will have to work. here I am testing a quick version of "reset one feature"

https://user-images.githubusercontent.com/19335151/161091087-99061226-921b-4567-8c97-114c8ba67c14.mp4

**Comment by riversn** [comment]
This stopped working, I really like the highlight +remove button you showed in this video.

**Comment by bradmartin333** [comment]
I never added it - video shows how it doesn't work
