### ISSUE TITLE
Resize X Axis by amount/direction HSpan is dragged

### ISSUE THREAD

**Issue by riversn** [bradmartin333/XferSuite#79]
When clicking and holding/dragging at the corners of the axises, stretch the plot by the amount moved. Without zooming.

Add right click option inside plot frame for 'reset axis to original'

![stretching graph](https://user-images.githubusercontent.com/101815602/158833971-898b02e7-7c1d-402a-99e3-896a0f23caf0.PNG)

**Comment by bradmartin333** [comment]
For item 1, this would cause overlapping UI refreshes
For item 2, I believe that function in the right click menu already exists.

**Comment by riversn** [comment]
Maybe if there's no way to smooth the stretching/dragging motion by 0.25% or something to make it controllable for the user, then atleast we need to add a right click on axis, Axis Options, Set min/max points for both X and Y axises.

**Comment by bradmartin333** [comment]
https://user-images.githubusercontent.com/19335151/159013712-6b5c1045-915e-4362-9c7f-2cf49481a33b.mp4

this look right? I was forgetting to reset the logic

**Comment by bradmartin333** [comment]
added ability to zoom on a single axis based on cursor position when using scroll wheel
