### ISSUE TITLE
Rename Grid Pitch to Unit pitch within array

### ISSUE THREAD

**Issue by riversn** [bradmartin333/XferSuite#80]
Rename Grid Pitch to Unit pitch within array. Maybe it'd be even better if the SEYR file saved the pitch distances somehow in the file and just auto imported it from the datasheet. and you don't need the user input then? idk.

![image](https://user-images.githubusercontent.com/101815602/158870171-9fb3282a-de4c-4d3d-b916-f86fd3331f5e.png)

**Comment by riversn** [comment]
Idk how that's going to work with multiple array sizes in the SEYR file though....

**Comment by bradmartin333** [comment]
I've experimented with this in the past by appending _0.xxx_0.yyy.txt to the end of the entered file name/string output file name. Can add back in as default for streaming output from XP.
