### ISSUE TITLE
Report Stamp Runout

### ISSUE THREAD

**Issue by riversn** [bradmartin333/XferSuite#82]
Report total magnitude position change between stamp pitches for X and Y directions. Can be done a few different ways.

For instance 10x10 array with 360um pitch. Perfect runout would be "0um" as in - if stamp post 0,0 is your starting position, stamp post 0,10 is exactly 3600um (360*10) in x direction from 0,0. If it was off, the position would be 3602 or 3599 and give a runout of "+2um", "-1um" respectively.

"Total amount that the post array stretched in X and Y directions"

one way to do it is maybe:
Avg left most column X position, then avg Right most column X position, then take the difference from the expected 'perfect pitch' applied to the avg of the left column.

**Comment by bradmartin333** [comment]
Stamp runout measurements are not valid on SPOT due to level of table. I've tried many times, but runout will have to be measured lithographically on a printer with a leveled stamp. That process can be automated.

**Comment by riversn** [comment]
Does SPOT not record positional data of the stamp posts? Level or not, if you have 3 samples with known distances, you can figure out the calibration offset and get your 'true' distance?

**Comment by bradmartin333** [comment]
It's complicated, but essentially no, SPOT does not provide XY positions of
stamp posts in a lithographic sense.
