### ISSUE TITLE
SEYR Image Viewer

### ISSUE THREAD

**Issue by riversn** [bradmartin333/XferSuite#83]
In a SERY run with multiple LED arrays in one 'unit'/part.

When reviewing data 'parsing in XferSuite':
I want to be able to zoom in on a point and visually see which LED is failing, not have them all plotting ontop of each other, but slightly offset by the same amount in the print recipe

**Comment by bradmartin333** [comment]
add after SEYR v1.3 release

**Comment by bradmartin333** [comment]
add with #98
