### ISSUE TITLE
Scatter Axis Reset

### ISSUE THREAD

**Issue by riversn** [bradmartin333/XferSuite#84]
in Parsed Row/Col Plot

Add revert axis/plot to original size when right clicking on axises/plot

**Comment by bradmartin333** [comment]
double middle mouse click does this. is that enough to close this? or would context menu option be better?

**Comment by riversn** [comment]
Double clicking on the plot or either axis do not revert axis/plot to original size

**Comment by bradmartin333** [comment]
middle mouse button (scroll wheel) double click - please try again

**Comment by bradmartin333** [comment]
did that work?

**Comment by riversn** [comment]
Middle Mouse button does work, a right click option would still be nice, especially for first time users

**Comment by bradmartin333** [comment]
add in #98

**Comment by riversn** [comment]
Need reset option on right click, not just hotkeys

**Comment by bradmartin333** [comment]
it's in #98
