### ISSUE TITLE
Flipped feature col grid pitch offset

### ISSUE THREAD

**Issue by riversn** [bradmartin333/XferSuite#85]
Inner Row/Col are plotted inverse. overall Region Row/Col is correct as is.

![image](https://user-images.githubusercontent.com/101815602/159537672-cc9a64f5-1d8b-474a-8c1a-cd1f64ae0855.png)

**Comment by bradmartin333** [comment]
okay - I see the issue with the x dir within images. easy fix, but will wait until other plot changes are made (switch from oxyplot to scottplot)

**Comment by riversn** [comment]
> okay - I see the issue with the x dir within images. easy fix, but will wait until other plot changes are made (switch from oxyplot to scottplot)

Whooot!

**Comment by bradmartin333** [comment]
fix with #98
