### ISSUE TITLE
Parse file on different thread

### ISSUE THREAD

**Issue by riversn** [bradmartin333/XferSuite#87]
After 3 'parseings' of a large dataset, no plot is displayed or plot is corrupted/messedup.

Closing the entire XferSuite app is fixes it

**Comment by riversn** [comment]
Common indicator of this problem is that when it happens, the box zones go black:

![image](https://user-images.githubusercontent.com/101815602/159542219-fdecdf96-0e91-4446-b938-c8c46b87ce59.png)

**Comment by riversn** [comment]
It also closes all open plots. idk if something is timing out or what.

**Comment by bradmartin333** [comment]
very strange - please upload video of it happening twice in a row with closing via task manager in between

**Comment by bradmartin333** [comment]
could not replicate - likely just a regular memory overflow being throttled by computer

**Comment by riversn** [comment]
I've been able to replicate this issue.

The black boxes happen when XferSuite is in the middle of yield calculation and the user click in the Buffer/Need box regions.
If the user clicks multiple times and there are already 5+ or more large parsed yield plots open, the program will crash entirely.
