### ISSUE TITLE
Copy Parse Plot as csv

### ISSUE THREAD

**Issue by riversn** [bradmartin333/XferSuite#91]
Add option to copy Parse plot as CSV (want row/col and Pass/fail), not just png.

**Comment by bradmartin333** [comment]
would this format work (in conjunction with #92)

X-Axis pos, Y-Axis pos, State

**Comment by riversn** [comment]
Add unit info infront of that and we're golden.

UnitName, UnitNumber, X-Axis pos, Y-Axis pos, State

**Comment by bradmartin333** [comment]
add with #98

**Comment by riversn** [comment]
Unit number is the master number of the individual unit inside the array. 

For instance, 1 image has 4 units (1 +3 copies). Unit 1, image 1, would be unit number 1. Unit 2, Image 1, would be unit number 2. **Unit 1 of Image 2, would be unit 5**.

**Comment by bradmartin333** [comment]
Each .seyr file has 1 grid
a grid is made up of tiles
a tile is made up of features
when parsed in xfersuite, each tile is scored "Pass" or "Fail" based on the chosen buckets and criteria in the XferSuite Parse SEYR window

**Comment by bradmartin333** [comment]
I think the csv you need is the SEYR report. with #98, I can make a viewer that shows the tile data in the report that matches the scatterpoint. an automated version of this video:

https://user-images.githubusercontent.com/19335151/161027008-1ffedac2-950b-4764-be70-2ea2e43d04ec.mp4

**Comment by riversn** [comment]
I want basically an "Export as Cycle File" option. I want to use XferPrint to plot only fails from a seyr run, look at and review the parsed map, then have an option to output those fails as a cycle file so we can immediately start repair printing to those failing locations.

Unless you've changed something, the X-axis positions are not correctly reported in seyr output files.

The format we currently have of seyr output files is:

GlobalImageNumber, Unit Array Col, Unit Array Row. 

For a cycle file, I need:
Region Row, Region Col, Print Row, Print Row

But Row/Col info in Seyr outputs is only reporting 0,0?
![image](https://user-images.githubusercontent.com/101815602/161073758-81003407-b099-431a-b841-98d598a20f24.png)

**Comment by riversn** [comment]
If we have X-Axis pos, Y-Axis pos, State, then we just have to manipulate it by Num of Rows in 1 region, Number of Col in 1 region (which user can input) and then it should be able to output the manipulated Region Row, Region Col, Print Row, Print Row

**Comment by riversn** [comment]
X-Axis pos, Y-Axis pos, is fundamentally different than GlobalImageNumber, Unit Array Col, Unit Array Row which is the only usable thing seyr report is outputting at the moment

**Comment by bradmartin333** [comment]
When running from XferPrint, the SEYR report should have the RR RC R C info populates - so that is a XferPrint bug (Will add to SEYR External UI issues)

Then, based on the setup of the recipe, any given RR RC R C index should match a single image. In that case, the XY positions are just extra.

The XY positions should be legitimate, right? It's not perfect because the grid pitch offsets from a corner instead of a center, but it is relatively accurate (or should be).

**Comment by bradmartin333** [comment]
As far as this issue is concerned though, this is all the information currently available. Exporting as cycle file is a different task

**Comment by riversn** [comment]
Exporting as a cycle file is simply, "export plot as CSV" as long as the output is in cyclefile notation (trr,tcc,tr,tc) and if the plot is plotted as x-axis post starting a 0,0 vs y-axis pos starting at 0,0 (#92)

**Comment by riversn** [comment]
Exporting as CSV without trr,tcc would just return the true x&y-axis postions as 0,0 (not the 180-210mm chuck positions)

**Comment by bradmartin333** [comment]
the xy positions in the .seyr report are true chuck positions from the metro run and the input would be automatic from XferPrint to the .sery report (would just copy the cycle file position - specific images are referenced by the SR SC / stamp row stamp col)
