### ISSUE TITLE
Ability to view axes in RR RC R C notation

### ISSUE THREAD

**Issue by riversn** [bradmartin333/XferSuite#92]
Option to either plot positions as reported by SEYR (currently) or plot bottom left position as 1,1 and then all positions increment from that. (See image)

![image](https://user-images.githubusercontent.com/101815602/159968741-3b38bf93-dd20-443d-9da5-bc194ea9627f.png)

**Comment by bradmartin333** [comment]
so you want to be able to choose the source of the X and Y axis data, correct?

**Comment by riversn** [comment]
I'm not entirely sure.. I want the array info to match production thinking - if the bottom left of the wafer is 0,0 in stamp/printing world, then I want to be reporting in that same mindframe, or atleast have the option to

**Comment by bradmartin333** [comment]
add with #98
