### ISSUE TITLE
Expand PixelPitch calculator tool across UI

### ISSUE THREAD

**Issue by riversn** [bradmartin333/XferSuite#93]
Would be great if it would be automatic, but maybe in meantime this is a workaround? Part of this is to help seyr plot subunits as separate locations on the parse map. 

When parsing a dataset with multiple units, allow user to input subunit pitches alongside global array pitch (grid Pitch).

![image](https://user-images.githubusercontent.com/101815602/160171520-37dc7101-d708-4679-a7b1-a8d37f4438a2.png)

It would absolutely be wonderful if it could auto-calculate the subunit pitches based on the .SERY/report once user inputs the global array pitches.
For instance: global pitch is 120umx60um, but seyr has pitches of 76x38. take user input of grid pitch (120x60) and ratio it to the 76x38 seyr number. Then apply subunit offset differences by that ratio. 
![image](https://user-images.githubusercontent.com/101815602/160171720-49a740dc-104d-42ba-9c27-143dd9a509bf.png)

Maybe instead have a user fillable entry in the .seyr which allows the user to input the 'real life' unit pitches and then the sery reports those values out in the report file. then Xfersuite can just input those values.

**Comment by bradmartin333** [comment]
This is SEYR related, and XferSuite won't be plotting individual features, only scored tiles - image inspection in #83 would be the way to see "deeper"

**Comment by riversn** [comment]
@bradmartin333 This is what we talked about today. We want to be able to plot all individual array units separately, not grouped together in a 'pass /fail grouped unit'. 

This could be done a number of ways, one is all the offset data can be user submitted (see potential 1st image above^ with subunit grid inputs) and that would be able to apply offsets  to the parsed plot, but it would be better if SEYR output contained offset data based on the seyr recipe and could autocalculate the offsets and apply it to the parsed map.

**Comment by bradmartin333** [comment]
combining this with #103, yeah? custom features?
