### ISSUE TITLE
Pass/Fail not updating when user clicks and drags in parsed map

### ISSUE THREAD

**Issue by riversn** [bradmartin333/XferSuite#96]
Clicking in a pass location will correctly pop up location data and state info, if user drags to another point, state is not being updated but location is.

![image](https://user-images.githubusercontent.com/101815602/160675645-62b318e0-7393-4b51-999c-7159b113ae5f.png)

**Comment by bradmartin333** [comment]
add with #98

**Comment by bradmartin333** [comment]
I now know why this is happening - unable to be fixed in current state. Releasing mouse and re-clicking will have to work until #98  is finished.
