### ISSUE TITLE
allow axis to slide by dragging

### ISSUE THREAD

**Issue by riversn** [bradmartin333/XferSuite#97]
Allow user to drag and move axis by dragging axis in parsed map. Currently only way to move and look around is to use scroll wheel in and out.

**Comment by bradmartin333** [comment]
add with #98

**Comment by bradmartin333** [comment]
see pan:

Pan* | Right mouse button
Zoom* | Mouse wheel
Zoom by rectangle* | Ctrl+Right mouse button, Middle mouse button
Reset* | Ctrl+Right mouse button double-click, Middle mouse button double-click
Show ‘tracker’ | Left mouse button
Reset axes | ‘A’, Home
Copy code | Ctrl+Alt+C
Copy properties | Ctrl+Alt+R
